[tool.poetry]
name = "cars"
version = "0.1.0"
description = ""
authors = ["Ula <ula.malin35@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.1.1"
pyright = "^1.1.359"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
